Repository paulpfeister/exam-autograder, pull requests merged in 2021-11, with the labels that each got.

#19 Feature/base ahmed new
  common/authn.php
  common/header-login.php
  common/new-question.php
  common/qbank-check.php
  srv_utils/dbconfig.php
Labels: enhancement

#21 Add sessions
  common/authn.php
  common/header-login.php
  srv_utils/dbconfig.php
Labels: enhancement

#23 Sessions
  common/header-internal.php
  common/header-login.php
  common/new-question.php
Labels: enhancement

#25 Preparing for rc1
  README.md
  common/footer.php
  common/header-internal.php
  common/header-login.php
  common/new-question.php
  common/qbank-check.php
  courses/courses.css
  courses/index.php
  index.html
  index.php
  instructors/index.php
  instructors/new-question/index.php
  srv_utils/dbconfig.php
  styles/colors.css
  styles/fonts.css
  styles/forms.css
  styles/master.css
Labels: enhancement

#26 Possible auth fix
  common/header-internal.php
  common/header-login.php
Labels: bug, enhancement

#31 Dynamically update assignment selection
  README.md
  common/header-internal.php
  common/header-login.php
  courses/index.php
  home/index.php
  home/user-home.css
  styles/master.css
Labels: documentation, enhancement

#34 Dynamic assignment loading
  README.md
  assignments/assignments.css
  assignments/index.php
  common/header-internal.php
  common/header-login.php
  home/index.php
  styles/master.css
Labels: documentation, enhancement

#35 Implement grading
  assignments/index.php
  assignments/submit-answer.php
  index.php
Labels: enhancement

#37 Prep for storing answers
  assignments/submit-answer.php
Labels: enhancement

#38 Finish grading
  assignments/index.php
  assignments/submit-answer.php
Labels: enhancement

#41 Add instructor toolbar
  assignments/instructor-toolbar.php
  assignments/new/index.php
  home/index.php
  home/user-home.css
Labels: enhancement

#42 Fix auto-population of assignments and creation of assignments
  assignments/index.php
  assignments/instructor-toolbar.php
  assignments/new/index.php
  assignments/new/new-assignment.css
Labels: enhancement
